### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by DuanhaoranCC** [THUDM/GraphMAE#20]
Hi and thanks for your work!
What is the difference between GraphMAE and the baseline model AttrMask in transfer learning?

**Comment by THINK2TRY** [comment]
@DuanhaoranCC Thanks for your attention. There are two differences between GraphMAE and AttrMask:
1. GraphMAE uses a GNN as the decoder, and AttrMask uses a linear layer for decoding.
2. Scaled cosine error (SCE) is used as the criterion in GraphMAE rather than cross-entropy in AttrMask.
We haven't conducted rigorous ablation studies to measure the single contribution of each component, but the overall training paradigm of GraphMAE achieves better results than AttrMask.
